const verbs = {
  namespaced: true,
  state: {    
    verbs: [
      {"id":1,  name: "ser", meaning   :"to be ", type: "irregular"},
      {"id":2,  name: "haber", meaning: "to have (to do something, auxiliary verb) ", type: "irregular"},
      {"id":3,  name: "estar", meaning: "to be (health, location, state) ", type: "irregular"},
      {"id":4,  name: "tener", meaning: "to have ", type: "irregular"},
      {"id":5,  name: "hacer", meaning: "", type: "irregular"},
      {"id":6,  name: "poder", meaning: "", type: "irregular"},
      {"id":7,  name: "decir", meaning: "to say, tell ", type: "irregular"},
      {"id":8,  name: "to", meaning: "go ", type: "irregular"},
      {"id":9,  name: "ver", meaning:  "to see", type: "irregular"}, 
      {"id":10, name: "dar", meaning:  "to give", type: "irregular"}, 
      {"id":11, name: "saber", meaning: "to know (information)", type: "irregular"},
      {"id":12, name: "querer", meaning: "to want, love ", type: "irregular"},
      {"id":13, name: "llegar", meaning: "to arrive, come, reach ", type: "irregular"},
      {"id":14, name: "pasar", meaning: "to pass, to spend (time), to happen ", type: "regular"},
      {"id":15, name: "deber", meaning: "to owe, must, should, ought to ", type: "regular"},
      {"id":16, name: "poner", meaning: "to put, place, set ", type: "irregular"},
      {"id":17, name: "parecer", meaning: "to seem, appear ", type: "irregular"},
      {"id":18, name: "quedar", meaning: "to stay, remain ", type: "regular"},
      {"id":19, name: "creer", meaning: "to believe ", type: "irregular"},
      {"id":20, name: "hablar", meaning: "to speak ", type: "regular"},
      {"id":21, name: "llevar", meaning: "to carry, bring ", type: "regular"},
      {"id":22, name: "dejar", meaning: "to leave, abandon, to let, allow ", type: "regular"},
      {"id":23, name: "seguir", meaning: "to follow, continue ", type: "irregular"},
      {"id":24, name: "encontrar", meaning: "to find, encounter ", type: "irregular"},
      {"id":25, name: "llamar", meaning: "to call, to name ", type: "regular"},
      {"id":26, name: "venir", meaning: ""},
      {"id":27, name: "pensar", meaning: "to think "},
      {"id":28, name: "salir", meaning: "to leave, go out "},
      {"id":29, name: "volver", meaning: "to return, go back "},
      {"id":30, name: "tomar", meaning: "to take, drink "},
      {"id":31, name: "conocer", meaning: "to know (people, places) "},
      {"id":32, name: "vivir", meaning: "to live "},
      {"id":33, name: "sentir", meaning: "to feel, regret "},
      {"id":34, name: "tratar", meaning: "to treat, handle "},
      {"id":35, name: "mirar", meaning: "to watch, look at "},
      {"id":36, name: "contar", meaning: "to count, relate, tell "},
      {"id":37, name: "empezar", meaning: "to begin, start "},
      {"id":38, name: "esperar", meaning: "to wait for, to hope "},
      {"id":39, name: "buscar", meaning: "to search for, look for "},
      {"id":40, name: "existir", meaning: "to exist "},
      {"id":41, name: "entrar", meaning: "to enter, go in, come in "},
      {"id":42, name: "trabajar", meaning: "to work "},
      {"id":43, name: "escribir", meaning: "to write "},
      {"id":44, name: "perder", meaning: "to lose "},
      {"id":45, name: "producir", meaning: "to produce "},
      {"id":46, name: "ocurrir", meaning: "to occur, happen "},
      {"id":47, name: "entender", meaning: "to understand "},
      {"id":48, name: "pedir", meaning: "to request, ask for "},
      {"id":49, name: "recibir", meaning: "to receive, to welcome, greet "},
      {"id":50, name: "recordar", meaning: "to remember, remind "},
      {"id":51, name: "terminar", meaning: "to finish, end "},
      {"id":52, name: "permitir", meaning: "to permit, allow "},
      {"id":53, name: "aparecer", meaning: "to appear, show up "},
      {"id":54, name: "conseguir", meaning: "to get, obtain "},
      {"id":55, name: "comenzar", meaning: "to begin, start, commence "},
      {"id":56, name: "servir", meaning: "to serve "},
      {"id":57, name: "sacar", meaning: "to take out, stick out "},
      {"id":58, name: "necesitar", meaning: "to need, require "},
      {"id":59, name: "mantener", meaning: "to maintain, get "},
      {"id":60, name: "resultar", meaning: "to turn out (to be) "},
      {"id":61, name: "leer", meaning: "to read "},
      {"id":62, name: "caer", meaning: "to fall "},
      {"id":63, name: "cambiar", meaning: "to change "},
      {"id":64, name: "presentar", meaning: "to introduce "},
      {"id":65, name: "crear", meaning: "to create, to make "},
      {"id":66, name: "abrir", meaning: "to open "},
      {"id":67, name: "considerar", meaning: "to consider "},
      {"id":68, name: "to", meaning: "hear "},
      {"id":69, name: "acabar", meaning: "to finish, end "},
      {"id":70, name: "convertir", meaning: "to convert, change "},
      {"id":71, name: "ganar", meaning: "to win, gain, earn, get, acquire "},
      {"id":72, name: "formar", meaning: "to form, shape, fashion, make "},
      {"id":73, name: "traer", meaning: "to bring, to get, fetch, to carry "},
      {"id":74, name: "partir", meaning: "to divide, to leave "},
      {"id":75, name: "morir", meaning: "to die "},
      {"id":76, name: "aceptar", meaning: "to accept, approve, to agree to "},
      {"id":77, name: "realizar", meaning: "to achieve, attain, accomplish "},
      {"id":78, name: "suponer", meaning: "to suppose "},
      {"id":79, name: "comprender", meaning: "to understand, comprehend "},
      {"id":80, name: "lograr", meaning: "to get, obtain, to achieve, attain "},
      {"id":81, name: "explicar", meaning: "to explain "},
      {"id":82, name: "preguntar", meaning: "to ask, inquire "},
      {"id":83, name: "tocar", meaning: "to touch, to play (an instrument) "},
      {"id":84, name: "reconocer", meaning: "to recognize "},
      {"id":85, name: "estudiar", meaning: "to study "},
      {"id":86, name: "alcanzar", meaning: "to reach, catch up "},
      {"id":87, name: "nacer", meaning: "to be born "},
      {"id":88, name: "dirigir", meaning: "to direct "},
      {"id":89, name: "correr", meaning: "to run "},
      {"id":90, name: "utilizar", meaning: "to use, utilize "},
      {"id":91, name: "pagar", meaning: "to pay, pay for "},
      {"id":92, name: "ayudar", meaning: "to help "},
      {"id":93, name: "gustar", meaning: "to please, be pleasing "},
      {"id":94, name: "jugar", meaning: "to play (a game or sport) "},
      {"id":95, name: "escuchar", meaning: "to listen, hear "},
      {"id":96, name: "cumplir", meaning: "to fulfil, carry out "},
      {"id":97, name: "ofrecer", meaning: "to offer "},
      {"id":98, name: "descubrir", meaning: "to discover "},
      {"id":99, name: "levantar", meaning: "to raise, to lift "}
    ],
    //filter: 'todos'
    search: '',
    watchedVideos: [
      {id: 1, link: 'https://www.youtube.com/watch?v=bUC_IwIEi68', 
        title: 'Noticias Telemundo, 15 de septiembre de 2018 | Noticiero | Telemundo', 
        type: 'noticias'},
      {id: 2, link: 'https://www.youtube.com/watch?v=f7emtj58YeM', 
        title: '103- Los 10 hábitos de un buen estudiante de español [podcast]', 
        type: 'espanol automatico'},
      {id: 3, link: 'https://www.youtube.com/watch?v=zMYQHkuLZv4', 
        title: '104- 9 razones por las que aún no hablas español con fluidez [podcast]', 
        type: 'espanol automatico'},
    ]
  },
  mutations: {
    search(state, val) {
      state.search = val;
    }
  },
  actions: {
     
  },
  getters: {
    verbs: state => state.verbs,
    search: state => state.search
  }
}

export default verbs