const verbs = [
  {"id":1, "ser"   :"to be "},
  {"id":2, "haber":"to have (to do something, auxiliary verb) "},
  {"id":3, "estar":"to be (health, location, state) "},
  {"id":4, "tener":"to have "},
  {"id":5, "hacer":""},
  {"id":6, "poder":""},
  {"id":7, "decir":"to say, tell "},
  {"id":8, "to":"go "},
  {"id":9, "ver": "to see"}, 
  {"id":10,"dar": "to give"}, 
  {"id":11,"saber":"to know (information)"},
  {"id":12,"querer":"to want, love "},
  {"id":13,"llegar":"to arrive, come, reach "},
  {"id":14,"pasar":"to pass, to spend (time), to happen "},
  {"id":15,"deber":"to owe, must, should, ought to "},
  {"id":16,"poner":"to put, place, set "},
  {"id":17,"parecer":"to seem, appear "},
  {"id":18,"quedar":"to stay, remain "},
  {"id":19,"creer":"to believe "},
  {"id":20,"hablar":"to speak "},
  {"id":21,"llevar":"to carry, bring "},
  {"id":22,"dejar":"to leave, abandon, to let, allow "},
  {"id":23,"seguir":"to follow, continue "},
  {"id":24,"encontrar":"to find, encounter "},
  {"id":25,"llamar":"to call, to name "},
  {"id":26,"venir":""},
  {"id":27,"pensar":"to think "},
  {"id":28,"salir":"to leave, go out "},
  {"id":29,"volver":"to return, go back "},
  {"id":30,"tomar":"to take, drink "},
  {"id":31,"conocer":"to know (people, places) "},
  {"id":32,"vivir":"to live "},
  {"id":33,"sentir":"to feel, regret "},
  {"id":34,"tratar":"to treat, handle "},
  {"id":35,"mirar":"to watch, look at "},
  {"id":36,"contar":"to count, relate, tell "},
  {"id":37,"empezar":"to begin, start "},
  {"id":38,"esperar":"to wait for, to hope "},
  {"id":39,"buscar":"to search for, look for "},
  {"id":40,"existir":"to exist "},
  {"id":41,"entrar":"to enter, go in, come in "},
  {"id":42,"trabajar":"to work "},
  {"id":43,"escribir":"to write "},
  {"id":44,"perder":"to lose "},
  {"id":45,"producir":"to produce "},
  {"id":46,"ocurrir":"to occur, happen "},
  {"id":47,"entender":"to understand "},
  {"id":48,"pedir":"to request, ask for "},
  {"id":49,"recibir":"to receive, to welcome, greet "},
  {"id":50,"recordar":"to remember, remind "},
  {"id":51,"terminar":"to finish, end "},
  {"id":52,"permitir":"to permit, allow "},
  {"id":53,"aparecer":"to appear, show up "},
  {"id":54,"conseguir":"to get, obtain "},
  {"id":55,"comenzar":"to begin, start, commence "},
  {"id":56,"servir":"to serve "},
  {"id":57,"sacar":"to take out, stick out "},
  {"id":58,"necesitar":"to need, require "},
  {"id":59,"mantener":"to maintain, get "},
  {"id":60,"resultar":"to turn out (to be) "},
  {"id":61,"leer":"to read "},
  {"id":62,"caer":"to fall "},
  {"id":63,"cambiar":"to change "},
  {"id":64,"presentar":"to introduce "},
  {"id":65,"crear":"to create, to make "},
  {"id":66,"abrir":"to open "},
  {"id":67,"considerar":"to consider "},
  {"id":68,"to":"hear "},
  {"id":69,"acabar":"to finish, end "},
  {"id":70,"convertir":"to convert, change "},
  {"id":71,"ganar":"to win, gain, earn, get, acquire "},
  {"id":72,"formar":"to form, shape, fashion, make "},
  {"id":73,"traer":"to bring, to get, fetch, to carry "},
  {"id":74,"partir":"to divide, to leave "},
  {"id":75,"morir":"to die "},
  {"id":76,"aceptar":"to accept, approve, to agree to "},
  {"id":77,"realizar":"to achieve, attain, accomplish "},
  {"id":78,"suponer":"to suppose "},
  {"id":79,"comprender":"to understand, comprehend "},
  {"id":80,"lograr":"to get, obtain, to achieve, attain "},
  {"id":81,"explicar":"to explain "},
  {"id":82,"preguntar":"to ask, inquire "},
  {"id":83,"tocar":"to touch, to play (an instrument) "},
  {"id":84,"reconocer":"to recognize "},
  {"id":85,"estudiar":"to study "},
  {"id":86,"alcanzar":"to reach, catch up "},
  {"id":87,"nacer":"to be born "},
  {"id":88,"dirigir":"to direct "},
  {"id":89,"correr":"to run "},
  {"id":90,"utilizar":"to use, utilize "},
  {"id":91,"pagar":"to pay, pay for "},
  {"id":92,"ayudar":"to help "},
  {"id":93,"gustar":"to please, be pleasing "},
  {"id":94,"jugar":"to play (a game or sport) "},
  {"id":95,"escuchar":"to listen, hear "},
  {"id":96,"cumplir":"to fulfil, carry out "},
  {"id":97,"ofrecer":"to offer "},
  {"id":98,"descubrir":"to discover "},
  {"id":99,"levantar":"to raise, to lift "}]

module.exports = 
  {verbs}